### ISSUE TITLE
Cannot Download Checkpoint

### ISSUE THREAD

**Issue by CeciLyu** [jas-preet/SPOT-1D-LM#2]
Hi,

I am trying to download the checkpoint, but this error message showed up:

wget https://servers.sparks-lab.org/downloads/SPOT-LM-checkpoints.xz
--2022-05-13 14:33:47--  https://servers.sparks-lab.org/downloads/SPOT-LM-checkpoints.xz
Resolving servers.sparks-lab.org (servers.sparks-lab.org)... 172.64.80.1, 2606:4700:130:436c:6f75:6466:6c61:7265
Connecting to servers.sparks-lab.org (servers.sparks-lab.org)|172.64.80.1|:443... connected.
HTTP request sent, awaiting response... 522 
2022-05-13 14:34:18 ERROR 522: (no description).

Could you please help me resolve this?

Thanks!

**Comment by jas-preet** [comment]
Apologies for the inconvenience. Previously the server was down. Now it should be working. Cheers
