### ISSUE TITLE
Model Checkpoints Unavailable

### ISSUE THREAD

**Issue by sroseallen** [jas-preet/SPOT-1D-LM#7]
Hello, I am having trouble downloading the model checkpoints (which are needed to run the run_inference .py file) - below is the error code I am getting using Ubuntu:

wget https://servers.sparks-lab.org/downloads/SPOT-LM-checkpoints.xz
--2023-08-30 18:05:52--  https://servers.sparks-lab.org/downloads/SPOT-LM-checkpoints.xz 
Resolving servers.sparks-lab.org (servers.sparks-lab.org)... 172.67.130.213, 104.21.3.148, 2606:4700:3031::6815:394, ...
Connecting to servers.sparks-lab.org (servers.sparks-lab.org)|172.67.130.213|:443... connected.
HTTP request sent, awaiting response... 522
2023-08-30 18:06:24 ERROR 522: (no description).

Please could you resolve this or provide a working link?
Thank you!

**Comment by lm-jkominek** [comment]
I am not the author, and I am not sure if you still care after all this time, but just wanted to let you know that the SPOT-1D-LM model checkpoints can be downloaded from this location - https://apisz.sparks-lab.org:8443/downloads/Resource/Protein/2_Protein_local_structure_prediction/SPOT-LM-checkpoints.xz

(luckily someone had a similar issue with SPOT-1D-Single, and got an answer - https://github.com/jas-preet/SPOT-1D-Single/issues/2)

**Comment by sroseallen** [comment]
thank you so much! that's really helpful :)

**Comment by sroseallen** [comment]
thank you so much! That's really helpful :)
